import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/component/nav";
const inter = Inter({ subsets: ["latin"] });
import Footer from "@/component/footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Nav />
      <body className={inter.className}>{children}</body>
      <Footer></Footer>
    </html>
  );
}
